---
- hosts: all
  become: true

  tasks:
    - name: Stop the running docker
      shell: docker stop treasurehunt
    - name: Remove the docker
      shell: docker rm -f treasurehunt
    - name: Remove image of the docker
      shell: docker image rm -f vazravasu/treasurehunt:latest

    - name: Download the latest docker and run
      shell: docker run -d -p 2000:2000 --name treasurehunt vazravasu/treasurehunt:latest
